"""Init migrations

Revision ID: a9bc2f43f378
Revises: 
Create Date: 2026-09-30 11:01:48.809405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9bc2f43f378'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TENANTS',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PRODUCTS',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['TENANTS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_tenant_id', 'PRODUCTS', ['tenant_id'], unique=False)
    op.create_table('SALES',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('approved', 'declined', 'unknown', name='SALES_STATUS'), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['TENANTS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_tenant_id', 'SALES', ['tenant_id'], unique=False)
    op.create_index('ux_sales_tenant_idempotency_key', 'SALES', ['tenant_id', 'idempotency_key'], unique=True)
    op.create_table('SALES_OUTBOX',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('approved', 'declined', 'unknown', name='SALES_STATUS'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['SALES.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['TENANTS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_outbox_tenant_id', 'SALES_OUTBOX', ['tenant_id'], unique=False)
    op.create_index('ix_sales_outbox_unprocessed', 'SALES_OUTBOX', ['processed_at', 'id'], unique=False)
    op.create_table('SALES_PRODUCTS',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['PRODUCTS.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['SALES.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_id', 'product_id')
    )
    op.create_index('ix_sales_products_sale_id', 'SALES_PRODUCTS', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_products_sale_id', table_name='SALES_PRODUCTS')
    op.drop_table('SALES_PRODUCTS')
    op.drop_index('ix_sales_outbox_unprocessed', table_name='SALES_OUTBOX')
    op.drop_index('ix_sales_outbox_tenant_id', table_name='SALES_OUTBOX')
    op.drop_table('SALES_OUTBOX')
    op.drop_index('ux_sales_tenant_idempotency_key', table_name='SALES')
    op.drop_index('ix_sales_tenant_id', table_name='SALES')
    op.drop_table('SALES')
    op.drop_index('ix_products_tenant_id', table_name='PRODUCTS')
    op.drop_table('PRODUCTS')
    op.drop_table('TENANTS')
    # ### end Alembic commands ###
